import { CURRENCY_BASE_URL } from '../../CONSTANTS';

export const FETCH_ANALYSIS = "FETCH_ANALYSIS";
export const FETCH_ANALYSIS_FULFILLED = "FETCH_ANALYSIS_FULFILLED";
export const FETCH_ANALYSIS_REJECTED = "FETCH_ANALYSIS_REJECTED";
export const ANALYSIS_URL = CURRENCY_BASE_URL+"/currency/views";
